$: dropin.recipes/Automations/Deployment

services:
  kiwi-bundle:
    context: .

    runtime: { name: node }

    tasks:
      start:
        name: Watch and build
        command: start

      build:
        name: Build production files
        command: build
