language: node_js
node_js: "lts/*"

cache:
  yarn: true
  directories:
    - node_modules
    - lib

stages:
  - init
  - build
  - deploy

install: echo Skipping Travis CI install...

jobs:
  include:  
    - name: Install, test and build
      stage: init
      script:
        - yarn install
        - yarn test
        - yarn build

    - name: NPM deploy
      stage: deploy
      if: tag IS present
      on:
        branch: master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
