language: node_js
node_js: "lts/*"

cache:
  yarn: true
  directories:
    - node_modules
    - lib

stages:
  - name: init
  - name: build
    if: branch = develop AND type IS present
  - name: deploy
    if: branch = develop AND type IS present

install: echo Skipping Travis CI install...

jobs:
  include:
    - name: Install & test
      stage: init
      script:
        - yarn install
        - yarn test

    - name: TypeScript build
      stage: build
      script: yarn build

    - name: NPM deploy
      stage: deploy
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
